//! Integration tests using real ZTF photometry from photo_events.
//!
//! Test fixtures are generated by `tests/gen_test_fixtures.py` from
//! /fred/oz480/mcoughli/AppleCider/photo_events NPZ files.
//!
//! Run:
//!   cargo test --release --test test_real_data -- --nocapture
//!   cargo test --release --test test_real_data large -- --ignored --nocapture

use lightcurve_fitting::{
    build_mag_bands, fit_nonparametric, fit_thermal,
    NonparametricBandResult, BandData,
};
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Load fixtures
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize)]
struct SourceFixture {
    obj_id: String,
    #[allow(dead_code)]
    label: i64,
    #[serde(default)]
    label_name: String,
    bands: HashMap<String, BandValues>,
}

#[derive(serde::Deserialize)]
struct BandValues {
    times: Vec<f64>,
    values: Vec<f64>,
    errors: Vec<f64>,
}

fn load_fixtures(name: &str) -> Vec<SourceFixture> {
    let base = env!("CARGO_MANIFEST_DIR");
    let path = format!("{}/tests/fixtures/{}", base, name);
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("Failed to read {} — run: python3 tests/gen_test_fixtures.py", path));
    serde_json::from_str(&data).expect("Failed to parse fixtures JSON")
}

fn load_small_fixtures() -> Vec<SourceFixture> {
    load_fixtures("real_sources.json")
}

fn load_large_fixtures() -> Vec<SourceFixture> {
    load_fixtures("real_sources_1000.json")
}

/// Build mag bands with short band names (g, r, i) that fit_thermal expects.
fn fixture_to_mag_bands(src: &SourceFixture) -> HashMap<String, BandData> {
    let mut all_times = Vec::new();
    let mut all_mags = Vec::new();
    let mut all_errs = Vec::new();
    let mut all_bands = Vec::new();

    for (band_name, bv) in &src.bands {
        // Strip "ztf" prefix so thermal fitter can match g/r/i
        let short_name = band_name.strip_prefix("ztf").unwrap_or(band_name);
        for i in 0..bv.times.len() {
            all_times.push(bv.times[i]);
            all_mags.push(bv.values[i]);
            all_errs.push(bv.errors[i]);
            all_bands.push(short_name.to_string());
        }
    }

    build_mag_bands(&all_times, &all_mags, &all_errs, &all_bands)
}

// ---------------------------------------------------------------------------
// Small fixture tests (always run)
// ---------------------------------------------------------------------------

#[test]
fn nonparametric_real_data_produces_results() {
    let fixtures = load_small_fixtures();
    assert!(!fixtures.is_empty(), "No fixtures loaded");

    let mut success_count = 0;
    let mut total_bands = 0;

    for src in &fixtures {
        let mag_bands = fixture_to_mag_bands(src);
        let (results, gps) = fit_nonparametric(&mag_bands);

        total_bands += mag_bands.len();

        for result in &results {
            assert!(!result.band.is_empty());
            assert!(result.n_obs > 0);

            if result.n_obs >= 5 {
                assert!(
                    result.peak_mag.is_some(),
                    "{} band {}: peak_mag is None with {} obs",
                    src.obj_id, result.band, result.n_obs
                );
                success_count += 1;
            }
        }

        // Check GP production for bands with enough data
        let bands_with_data = mag_bands.values().filter(|b| b.times.len() >= 5).count();
        if bands_with_data > 0 && gps.is_empty() {
            eprintln!("  WARN {}: {} bands with >=5 obs but no GPs returned",
                src.obj_id, bands_with_data);
        }
    }

    eprintln!(
        "Nonparametric: {}/{} bands produced valid peak_mag across {} sources",
        success_count, total_bands, fixtures.len()
    );
    assert!(success_count > 0);
}

#[test]
fn nonparametric_features_are_physical() {
    let fixtures = load_small_fixtures();

    for src in &fixtures {
        let mag_bands = fixture_to_mag_bands(src);
        let (results, _) = fit_nonparametric(&mag_bands);

        for result in &results {
            if result.n_obs < 10 { continue; }

            if let Some(peak) = result.peak_mag {
                assert!(peak > 10.0 && peak < 30.0,
                    "{} band {}: peak_mag={} unphysical", src.obj_id, result.band, peak);
            }
            if let Some(chi2) = result.chi2 {
                assert!(chi2 >= 0.0,
                    "{} band {}: chi2={} negative", src.obj_id, result.band, chi2);
            }
            if let Some(rt) = result.rise_time {
                assert!(rt >= 0.0, "{} band {}: rise_time={} negative", src.obj_id, result.band, rt);
            }
            if let Some(dt) = result.decay_time {
                assert!(dt >= 0.0, "{} band {}: decay_time={} negative", src.obj_id, result.band, dt);
            }
            if let Some(vn) = result.von_neumann_ratio {
                assert!(vn > 0.0 && vn < 100.0,
                    "{} band {}: von_neumann_ratio={} out of range", src.obj_id, result.band, vn);
            }
        }
    }
}

#[test]
fn nonparametric_gp_predictions_consistent() {
    let fixtures = load_small_fixtures();

    let src = fixtures.iter()
        .find(|s| s.bands.values().any(|b| b.times.len() >= 20))
        .expect("No source with >= 20 obs");

    let mag_bands = fixture_to_mag_bands(src);
    let (_results, gps) = fit_nonparametric(&mag_bands);

    eprintln!("Testing GP consistency for {}", src.obj_id);

    for (band_name, gp) in &gps {
        if let Some(bd) = mag_bands.get(band_name) {
            let pred = gp.predict(&bd.times);
            let mut max_residual = 0.0f64;
            for i in 0..bd.values.len() {
                max_residual = max_residual.max((pred[i] - bd.values[i]).abs());
            }
            eprintln!("  {}: max_residual={:.4} mag ({} obs)", band_name, max_residual, bd.times.len());
            assert!(max_residual < 5.0,
                "{} band {}: GP max_residual={:.4} too large", src.obj_id, band_name, max_residual);
        }
    }
}

#[test]
fn nonparametric_serialization_roundtrip() {
    let fixtures = load_small_fixtures();
    let src = &fixtures[0];
    let mag_bands = fixture_to_mag_bands(src);
    let (results, _) = fit_nonparametric(&mag_bands);

    for result in &results {
        let json = serde_json::to_string(result).expect("serialization failed");
        let deser: NonparametricBandResult = serde_json::from_str(&json).expect("deserialization failed");

        assert_eq!(result.band, deser.band);
        assert_eq!(result.n_obs, deser.n_obs);
        match (result.peak_mag, deser.peak_mag) {
            (Some(a), Some(b)) => assert!((a - b).abs() < 1e-10),
            (None, None) => {},
            _ => panic!("peak_mag Some/None mismatch"),
        }
    }
}

#[test]
fn thermal_works_with_real_data() {
    let fixtures = load_small_fixtures();

    let mut thermal_success = 0;
    let mut thermal_attempts = 0;

    for src in &fixtures {
        let mag_bands = fixture_to_mag_bands(src);

        // Need >= 2 bands for thermal
        let usable_bands: Vec<&str> = ["g", "r", "i"].iter()
            .filter(|&&b| mag_bands.get(b).map_or(false, |d| d.times.len() >= 5))
            .copied()
            .collect();
        if usable_bands.len() < 2 { continue; }

        thermal_attempts += 1;

        // Fit nonparametric first, then thermal with prefit GPs
        let (_, gps) = fit_nonparametric(&mag_bands);
        let thermal = fit_thermal(&mag_bands, Some(&gps));

        if let Some(ref result) = thermal {
            thermal_success += 1;

            // log_temp_peak: log10(T) should give T in 500-200000 K range
            if let Some(log_t) = result.log_temp_peak {
                let t = 10.0_f64.powf(log_t);
                assert!(t > 500.0 && t < 200_000.0,
                    "{}: T_peak={:.0} K (log={:.3}) out of range", src.obj_id, t, log_t);
            }

            // Chi2 should be non-negative
            if let Some(chi2) = result.chi2 {
                assert!(chi2 >= 0.0,
                    "{}: thermal chi2={} negative", src.obj_id, chi2);
            }

            let t_peak = result.log_temp_peak.map(|lt| 10.0_f64.powf(lt)).unwrap_or(f64::NAN);
            let chi2 = result.chi2.unwrap_or(f64::NAN);
            eprintln!("  {} ({}): T_peak={:.0} K, chi2={:.4}, n_color_obs={}",
                src.obj_id, src.label_name, t_peak, chi2, result.n_color_obs);
        }
    }

    eprintln!("Thermal: {}/{} sources produced results", thermal_success, thermal_attempts);
    assert!(thermal_success > 0, "No thermal fits succeeded");
}

// ---------------------------------------------------------------------------
// Class-level feature validation (uses large fixture, always-run subset)
// ---------------------------------------------------------------------------

/// Helper: compute median of a f64 slice.
fn median(v: &[f64]) -> f64 {
    if v.is_empty() { return f64::NAN; }
    let mut sorted = v.to_vec();
    sorted.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    sorted[sorted.len() / 2]
}

/// Collect per-class feature medians from the large fixture.
/// Returns a map: class_name -> (med_fwhm, med_rise, med_decay, med_vn, med_mono, med_pl_idx).
fn class_feature_medians() -> HashMap<String, (f64, f64, f64, f64, f64, f64)> {
    let fixtures = load_large_fixtures();

    let mut features_by_class: HashMap<String, (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>)> =
        HashMap::new();

    for src in &fixtures {
        let mag_bands = fixture_to_mag_bands(src);
        let (results, _) = fit_nonparametric(&mag_bands);
        let class = if src.label_name.is_empty() {
            format!("label_{}", src.label)
        } else {
            src.label_name.clone()
        };

        let entry = features_by_class.entry(class).or_insert_with(|| {
            (Vec::new(), Vec::new(), Vec::new(), Vec::new(), Vec::new(), Vec::new())
        });

        for r in &results {
            if let Some(v) = r.fwhm { entry.0.push(v); }
            if let Some(v) = r.rise_time { entry.1.push(v); }
            if let Some(v) = r.decay_time { entry.2.push(v); }
            if let Some(v) = r.von_neumann_ratio { entry.3.push(v); }
            if let Some(v) = r.post_peak_monotonicity { entry.4.push(v); }
            if let Some(v) = r.decay_power_law_index { entry.5.push(v); }
        }
    }

    features_by_class.into_iter().map(|(k, (fwhm, rise, decay, vn, mono, pl))| {
        (k, (median(&fwhm), median(&rise), median(&decay), median(&vn), median(&mono), median(&pl)))
    }).collect()
}

#[test]
#[ignore]
fn agn_has_longest_timescales() {
    let medians = class_feature_medians();
    let (agn_fwhm, agn_rise, _, _, _, _) = medians["AGN"];

    // AGN should have longer timescales than any SN type
    for (class, &(fwhm, rise, _, _, _, _)) in &medians {
        if class.starts_with("SN") {
            assert!(agn_fwhm > fwhm,
                "AGN FWHM ({:.0}) should exceed {} FWHM ({:.0})", agn_fwhm, class, fwhm);
            assert!(agn_rise > rise,
                "AGN rise ({:.0}) should exceed {} rise ({:.0})", agn_rise, class, rise);
        }
    }
}

#[test]
#[ignore]
fn agn_most_stochastic_von_neumann() {
    let medians = class_feature_medians();
    let (_, _, _, agn_vn, _, _) = medians["AGN"];

    // AGN should have the highest von Neumann ratio (most stochastic)
    for (class, &(_, _, _, vn, _, _)) in &medians {
        if class != "AGN" && class != "Cataclysmic" {
            assert!(agn_vn > vn,
                "AGN vN ({:.3}) should exceed {} vN ({:.3})", agn_vn, class, vn);
        }
    }
}

#[test]
#[ignore]
fn snia_fastest_fwhm() {
    let medians = class_feature_medians();
    let (snia_fwhm, _, _, _, _, _) = medians["SN Ia"];

    // SN Ia should have the shortest FWHM of all SN types
    for (class, &(fwhm, _, _, _, _, _)) in &medians {
        if class.starts_with("SN") && class != "SN Ia" {
            assert!(snia_fwhm < fwhm,
                "SN Ia FWHM ({:.0}) should be shorter than {} ({:.0})", snia_fwhm, class, fwhm);
        }
    }
}

#[test]
#[ignore]
fn snia_highest_monotonicity() {
    let medians = class_feature_medians();
    let (_, _, _, _, snia_mono, _) = medians["SN Ia"];

    // SN Ia should have highest post-peak monotonicity (smooth decline)
    for (class, &(_, _, _, _, mono, _)) in &medians {
        if class != "SN Ia" {
            assert!(snia_mono > mono,
                "SN Ia monotonicity ({:.3}) should exceed {} ({:.3})", snia_mono, class, mono);
        }
    }
}

#[test]
#[ignore]
fn snia_steepest_power_law() {
    let medians = class_feature_medians();
    let (_, _, _, _, _, snia_pl) = medians["SN Ia"];

    // SN Ia should have the steepest power-law decay index
    for (class, &(_, _, _, _, _, pl)) in &medians {
        if class != "SN Ia" {
            assert!(snia_pl > pl,
                "SN Ia PL index ({:.3}) should exceed {} ({:.3})", snia_pl, class, pl);
        }
    }
}

#[test]
#[ignore]
fn thermal_tde_hottest() {
    let fixtures = load_large_fixtures();

    let mut temps_by_class: HashMap<String, Vec<f64>> = HashMap::new();

    for src in &fixtures {
        let mag_bands = fixture_to_mag_bands(src);
        let usable = ["g", "r", "i"].iter()
            .filter(|&&b| mag_bands.get(b).map_or(false, |d| d.times.len() >= 5))
            .count();
        if usable < 2 { continue; }

        let (_, gps) = fit_nonparametric(&mag_bands);
        if let Some(thermal) = fit_thermal(&mag_bands, Some(&gps)) {
            if let Some(log_t) = thermal.log_temp_peak {
                let t = 10.0_f64.powf(log_t);
                if t < 200_000.0 { // exclude boundary hits
                    let class = if src.label_name.is_empty() {
                        format!("label_{}", src.label)
                    } else {
                        src.label_name.clone()
                    };
                    temps_by_class.entry(class).or_default().push(t);
                }
            }
        }
    }

    let tde_med_t = median(&temps_by_class["TDE"]);

    // TDEs should be hotter than most SN types (except possibly IIb)
    for class in ["SN Ia", "SN II", "SN IIP", "SN Ic", "SN Ib"] {
        if let Some(temps) = temps_by_class.get(class) {
            let med = median(temps);
            assert!(tde_med_t > med,
                "TDE median T ({:.0} K) should exceed {} ({:.0} K)", tde_med_t, class, med);
        }
    }
}

// ---------------------------------------------------------------------------
// Large fixture tests (run with --ignored)
// ---------------------------------------------------------------------------

#[test]
#[ignore]
fn large_nonparametric_all_classes() {
    let fixtures = load_large_fixtures();

    eprintln!("\n{:=<80}", "");
    eprintln!("GP + Thermal reconstruction on {} real ZTF sources", fixtures.len());
    eprintln!("{:=<80}", "");

    // Per-class statistics
    struct ClassStats {
        label_name: String,
        n_sources: usize,
        n_bands_with_peak: usize,
        n_bands_total: usize,
        n_thermal: usize,
        n_thermal_attempts: usize,
        peak_mags: Vec<f64>,
        chi2s: Vec<f64>,
        rise_times: Vec<f64>,
        decay_times: Vec<f64>,
        fwhms: Vec<f64>,
        temperatures: Vec<f64>,
        thermal_chi2s: Vec<f64>,
        von_neumann_ratios: Vec<f64>,
        decay_pl_indices: Vec<f64>,
        post_peak_monotonicities: Vec<f64>,
    }

    let mut stats_by_class: HashMap<String, ClassStats> = HashMap::new();
    let mut total_panics = 0usize;
    let mut total_sources = 0usize;

    let t0 = std::time::Instant::now();

    for src in &fixtures {
        total_sources += 1;
        let mag_bands = fixture_to_mag_bands(src);
        let class = if src.label_name.is_empty() {
            format!("label_{}", src.label)
        } else {
            src.label_name.clone()
        };

        let stats = stats_by_class.entry(class.clone()).or_insert_with(|| ClassStats {
            label_name: class.clone(),
            n_sources: 0,
            n_bands_with_peak: 0,
            n_bands_total: 0,
            n_thermal: 0,
            n_thermal_attempts: 0,
            peak_mags: Vec::new(),
            chi2s: Vec::new(),
            rise_times: Vec::new(),
            decay_times: Vec::new(),
            fwhms: Vec::new(),
            temperatures: Vec::new(),
            thermal_chi2s: Vec::new(),
            von_neumann_ratios: Vec::new(),
            decay_pl_indices: Vec::new(),
            post_peak_monotonicities: Vec::new(),
        });

        stats.n_sources += 1;

        // Nonparametric
        let (results, gps) = fit_nonparametric(&mag_bands);

        for result in &results {
            stats.n_bands_total += 1;

            if result.peak_mag.is_some() {
                stats.n_bands_with_peak += 1;
            }

            // Collect feature distributions
            if let Some(v) = result.peak_mag { stats.peak_mags.push(v); }
            if let Some(v) = result.chi2 { stats.chi2s.push(v); }
            if let Some(v) = result.rise_time { stats.rise_times.push(v); }
            if let Some(v) = result.decay_time { stats.decay_times.push(v); }
            if let Some(v) = result.fwhm { stats.fwhms.push(v); }
            if let Some(v) = result.von_neumann_ratio { stats.von_neumann_ratios.push(v); }
            if let Some(v) = result.decay_power_law_index { stats.decay_pl_indices.push(v); }
            if let Some(v) = result.post_peak_monotonicity { stats.post_peak_monotonicities.push(v); }

            // Sanity checks — generous bounds for real data
            // Some AGN/cataclysmics can be very bright (mag < 10)
            // and some faint sources can be mag > 25
            if let Some(peak) = result.peak_mag {
                if !(peak > -10.0 && peak < 35.0) {
                    eprintln!("  WARN {}: {} peak_mag={:.2} out of range",
                        src.obj_id, result.band, peak);
                    total_panics += 1;
                }
            }
            if let Some(chi2) = result.chi2 {
                if chi2 < 0.0 {
                    eprintln!("  WARN {}: {} chi2={:.4} negative",
                        src.obj_id, result.band, chi2);
                    total_panics += 1;
                }
            }
        }

        // Thermal
        let usable = ["g", "r", "i"].iter()
            .filter(|&&b| mag_bands.get(b).map_or(false, |d| d.times.len() >= 5))
            .count();
        if usable >= 2 {
            stats.n_thermal_attempts += 1;
            if let Some(thermal) = fit_thermal(&mag_bands, Some(&gps)) {
                stats.n_thermal += 1;
                if let Some(log_t) = thermal.log_temp_peak {
                    let t = 10.0_f64.powf(log_t);
                    stats.temperatures.push(t);
                    // Note: some fits hit optimizer bounds (T=1e6 K).
                    // This is expected for poorly constrained single-color data.
                }
                if let Some(chi2) = thermal.chi2 {
                    stats.thermal_chi2s.push(chi2);
                }
            }
        }
    }

    let elapsed = t0.elapsed();

    // Print summary
    fn percentile(v: &[f64], p: f64) -> f64 {
        if v.is_empty() { return f64::NAN; }
        let mut sorted = v.to_vec();
        sorted.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
        let idx = ((p / 100.0) * (sorted.len() - 1) as f64) as usize;
        sorted[idx.min(sorted.len() - 1)]
    }

    fn median(v: &[f64]) -> f64 { percentile(v, 50.0) }

    eprintln!("\n{:-<100}", "");
    eprintln!("{:<15} {:>6} {:>8} {:>8} {:>8} {:>8} {:>10} {:>8} {:>8} {:>8} {:>8}",
        "Class", "N_src", "Bands", "Peak%", "Therm%",
        "Med_chi2", "Med_peak", "Med_rise", "Med_dec", "Med_T", "Med_vN");
    eprintln!("{:-<100}", "");

    let mut classes: Vec<_> = stats_by_class.values().collect();
    classes.sort_by(|a, b| a.label_name.cmp(&b.label_name));

    for s in &classes {
        let peak_pct = if s.n_bands_total > 0 {
            100.0 * s.n_bands_with_peak as f64 / s.n_bands_total as f64
        } else { 0.0 };
        let therm_pct = if s.n_thermal_attempts > 0 {
            100.0 * s.n_thermal as f64 / s.n_thermal_attempts as f64
        } else { 0.0 };

        eprintln!("{:<15} {:>6} {:>8} {:>7.1}% {:>7.1}% {:>10.4} {:>8.2} {:>8.1} {:>8.1} {:>8.0} {:>8.3}",
            s.label_name, s.n_sources, s.n_bands_total, peak_pct, therm_pct,
            median(&s.chi2s),
            median(&s.peak_mags),
            median(&s.rise_times),
            median(&s.decay_times),
            median(&s.temperatures),
            median(&s.von_neumann_ratios),
        );
    }

    eprintln!("\n{:-<100}", "");
    eprintln!("Discriminating features by class:");
    eprintln!("{:<15} {:>10} {:>10} {:>10} {:>10}",
        "Class", "Med_PL_idx", "Med_mono", "Med_FWHM", "Therm_chi2");
    eprintln!("{:-<100}", "");

    for s in &classes {
        eprintln!("{:<15} {:>10.3} {:>10.3} {:>10.1} {:>10.4}",
            s.label_name,
            median(&s.decay_pl_indices),
            median(&s.post_peak_monotonicities),
            median(&s.fwhms),
            median(&s.thermal_chi2s),
        );
    }

    let total_bands: usize = classes.iter().map(|s| s.n_bands_total).sum();
    let total_peaks: usize = classes.iter().map(|s| s.n_bands_with_peak).sum();
    let total_thermal: usize = classes.iter().map(|s| s.n_thermal).sum();

    eprintln!("\n{:=<80}", "");
    eprintln!("TOTALS: {} sources, {} bands ({} with peak = {:.1}%)",
        total_sources, total_bands, total_peaks,
        100.0 * total_peaks as f64 / total_bands.max(1) as f64);
    eprintln!("Thermal: {} successful fits", total_thermal);
    eprintln!("Warnings: {}", total_panics);
    eprintln!("Wall time: {:.2}s ({:.0} sources/sec)",
        elapsed.as_secs_f64(), total_sources as f64 / elapsed.as_secs_f64());
    eprintln!("{:=<80}", "");

    // Hard assertions
    assert!(total_panics == 0,
        "{} sources had out-of-range features — see warnings above", total_panics);
    assert!(total_peaks as f64 / total_bands as f64 > 0.8,
        "Peak detection rate {:.1}% is too low", 100.0 * total_peaks as f64 / total_bands as f64);
    assert!(total_thermal > 0, "No thermal fits succeeded at all");
}
